// <auto-generated />
using System;
using CSharp_Web_Workshop_ForumApp.Data;
using Forum.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharp_Web_Workshop_ForumApp.Data.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20230531155457_CreateAndSeedDb")]
    partial class CreateAndSeedDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CSharp_Web_Workshop_ForumApp.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d74612e-43ce-43b9-bf67-be6a38204515"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris id lobortis odio. Orci varius natoque penatibus et magnis dis parturient.",
                            Title = "My first post"
                        },
                        new
                        {
                            Id = new Guid("e6ca5ddb-fd60-4ca0-9614-23694b7d2a41"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec metus ipsum, scelerisque at velit ut, ultricies varius lorem.",
                            Title = "My second post"
                        },
                        new
                        {
                            Id = new Guid("106d87e9-acd8-4541-9868-b67d05bb5ec2"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam interdum consectetur dictum. Proin nisi.",
                            Title = "My third post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
